# Generated by Django 2.1.5 on 2019-02-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190210_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reside',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='거주지'),
        ),
    ]
