# Generated by Django 2.1.5 on 2019-02-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190210_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reside',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='거주지'),
        ),
    ]
