# Generated by Django 2.0.1 on 2019-02-17 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(help_text='내용을 최소 10자 이상으로 작성해주세요', validators=[django.core.validators.MinLengthValidator(10, message=None)], verbose_name='내용')),
                ('payment', models.CharField(choices=[('평범', '7500원 ~ 9000원'), ('굳', '9000원 ~ 10500원'), ('쏘 굳', '10500원 이상')], max_length=10, verbose_name='시급')),
                ('workplace', models.CharField(max_length=50, verbose_name='지점')),
                ('recommend', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('work_type', models.CharField(choices=[('외식/음료', '외식/음료'), ('유통/판매', '유통/판매'), ('문화/여가/생활', '문화/여가/생활'), ('서비스', '서비스'), ('사무직', '사무직'), ('고객상담/리서치/영업', '고객상담/리서치/영업'), ('생산/건설/노무', '생산/건설/노무'), ('IT/컴퓨터', 'IT/컴퓨터'), ('교육/강사', '교육/강사'), ('디자인', '디자인'), ('미디어', '미디어'), ('운전/배달', '운전/배달'), ('병원/간호/연구', '병원/간호/연구')], help_text='알바 직종을 선택해 주세요.', max_length=10, verbose_name='직종')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='published', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.Comment'),
        ),
    ]
