# Generated by Django 2.1.5 on 2019-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('payment', models.CharField(choices=[('평범', '7500원 ~ 9000원'), ('굳', '9000원 ~ 10500원'), ('쏘 굳', '10500원 이상')], max_length=1, verbose_name='시급')),
                ('workplace', models.CharField(max_length=50, verbose_name='지점')),
                ('recommend', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=5, verbose_name='별점')),
                ('work_type', models.CharField(choices=[('단기', '단기'), ('장기', '장기')], max_length=10, verbose_name='직종')),
            ],
        ),
    ]
