# Generated by Django 2.1.5 on 2019-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.CharField(choices=[('평범', '7500원 ~ 9000원'), ('굳', '9000원 ~ 10500원'), ('쏘 굳', '10500원 이상')], max_length=10, verbose_name='시급'),
        ),
    ]
