# Generated by Django 2.1.5 on 2019-02-10 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='내용을 최소 10자 이상으로 작성해주세요', validators=[django.core.validators.MinLengthValidator(10, message=None)], verbose_name='내용'),
        ),
    ]
