# Generated by Django 2.1.5 on 2019-02-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
