# Generated by Django 2.1.5 on 2019-02-06 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190207_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='내용을 최소 200자 이상으로 작성해주세요', validators=[django.core.validators.MinLengthValidator(200, message=None)], verbose_name='내용'),
        ),
    ]
