# Generated by Django 2.1.5 on 2019-02-08 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20190208_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='preference',
            name='post',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
