# Generated by Django 2.1.5 on 2019-02-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190219_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.CharField(choices=[('전체', '전체'), ('7500원~9000원', '7500~9000'), ('9000원~10500원', '9000~10500'), ('10500 이상', '10500원 이상')], max_length=20, verbose_name='시급'),
        ),
    ]
