# Generated by Django 2.1.5 on 2019-02-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190219_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment',
            field=models.CharField(choices=[('전체', '전체'), ('7500원~9000원', '7500원~9000원'), ('9000원~10500원', '9000원~10500원'), ('10500원 이상', '10500원 이상')], max_length=20, verbose_name='시급'),
        ),
    ]
