# Generated by Django 2.1.5 on 2019-02-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190220_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='workplace',
            field=models.CharField(choices=[('강남/서초/양재', '강남/서초/양재'), ('잠실/송파/강동', '잠실/송파/강동'), ('동작/관악/사당', '동작/관악/사당'), ('마포/서대문/은평', '마포/서대문/은평'), ('종로/중구/용산', '종로/중구/용산'), ('노원/도봉/강북/성북', '노원/도봉/강북/성북'), ('광진/성동/중랑/동대문', '광진/성동/중랑/동대문'), ('영등포/구로/신도림', '영등포/구로/신도림'), ('강서/금천/양천', '강서/금천/양천')], max_length=50, verbose_name='지점'),
        ),
    ]
