# Generated by Django 2.1.5 on 2019-02-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_post_author'),
        ('main', '0006_comment_reply'),
    ]

    operations = [
    ]
