# Generated by Django 2.1.5 on 2019-02-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_author'),
        ('main', '0007_merge_20190210_1537'),
    ]

    operations = [
    ]
