# Generated by Django 2.1.5 on 2019-02-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_author'),
        ('main', '0008_merge_20190210_1831'),
    ]

    operations = [
    ]
