# Generated by Django 2.1.5 on 2019-02-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190220_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='workplace',
            field=models.TextField(max_length=300, null=True, verbose_name='지점'),
        ),
    ]
