# Generated by Django 2.1.5 on 2019-02-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20190210_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
