# Generated by Django 2.1.5 on 2019-02-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190220_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='workplace',
        ),
        migrations.AddField(
            model_name='post',
            name='reside',
            field=models.TextField(max_length=50, null=True, verbose_name='지점'),
        ),
    ]
