# Generated by Django 2.1.5 on 2019-02-12 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190211_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recommend',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점'),
        ),
    ]
