# Generated by Django 2.1.5 on 2019-02-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190213_0145'),
        ('main', '0017_auto_20190212_2234'),
    ]

    operations = [
    ]
