# Generated by Django 2.1.5 on 2019-02-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_comment_likes'),
        ('main', '0020_auto_20190215_1528'),
    ]

    operations = [
    ]
