# Generated by Django 2.1.5 on 2019-02-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_merge_20190217_0406'),
        ('main', '0021_merge_20190215_1801'),
    ]

    operations = [
    ]
